"""Adapters that map existing AiNiee settings into MangaCore."""

from .configAdapter import build_cli_config_snapshot
from .providerAdapter import (
    RuntimeAssetStatus,
    RuntimeDependencyStatus,
    RuntimeDetectOutput,
    RuntimeDeviceStatus,
    RuntimeInpaintOutput,
    RuntimeOcrOutput,
    RuntimeRequirementStatus,
    download_runtime_assets,
    get_detect_runtime_ids,
    get_inpaint_runtime_id,
    get_ocr_runtime_id,
    get_runtime_asset_status,
    get_runtime_dependency_status,
    get_runtime_device_status,
    get_runtime_requirement_status,
    normalize_runtime_device,
    runtime_device_from_config,
    runtime_device_status_from_config,
    run_detect_runtime,
    run_inpaint_runtime,
    run_region_ocr_runtime,
)

__all__ = [
    "RuntimeAssetStatus",
    "RuntimeDependencyStatus",
    "RuntimeDetectOutput",
    "RuntimeDeviceStatus",
    "RuntimeInpaintOutput",
    "RuntimeOcrOutput",
    "RuntimeRequirementStatus",
    "build_cli_config_snapshot",
    "download_runtime_assets",
    "get_detect_runtime_ids",
    "get_inpaint_runtime_id",
    "get_ocr_runtime_id",
    "get_runtime_asset_status",
    "get_runtime_dependency_status",
    "get_runtime_device_status",
    "get_runtime_requirement_status",
    "normalize_runtime_device",
    "runtime_device_from_config",
    "runtime_device_status_from_config",
    "run_detect_runtime",
    "run_inpaint_runtime",
    "run_region_ocr_runtime",
]
