"""Validate and durably stage results returned by an external Agent.

This module is deliberately a boundary between the external Agent protocol and
the deterministic translation writer.  It validates a claimed batch against a
ledger, then writes an append-only task-local result document.  It never opens
or mutates ``CacheManager`` state and never writes a translated output file.
"""
from __future__ import annotations

from collections import Counter
from copy import deepcopy
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import re
import threading
from typing import Any, Callable, Mapping, Sequence


SCHEMA = "ainiee.external_agent.batch_result.v1"
_TASK_ID_RE = re.compile(r"[A-Za-z0-9][A-Za-z0-9_-]{0,127}\Z")
_SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")

# These are the placeholder forms generated by AiNiee's text processors and
# common provider prompts.  Matching counters preserves repeated placeholders.
_PLACEHOLDER_RE = re.compile(
    r"\[P\d+\]|↓+|\{\{[^{}\n]+\}\}|\$\{[^{}\n]+\}|%[A-Za-z0-9_.:-]+%"
)


class ExternalAgentBatchResultError(ValueError):
    """A result rejected before it can reach the deterministic writer."""

    def __init__(self, message: str, code: str = "INVALID_BATCH_RESULT") -> None:
        super().__init__(message)
        self.code = code

    def to_dict(self) -> dict[str, str]:
        return {"error_code": self.code, "message": str(self)}


BatchResultError = ExternalAgentBatchResultError


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def _canonical(value: Any) -> bytes:
    return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256(value: bytes | str) -> str:
    return hashlib.sha256(value.encode("utf-8") if isinstance(value, str) else value).hexdigest()


def _safe_task_id(value: Any) -> str:
    if not isinstance(value, str) or not _TASK_ID_RE.fullmatch(value):
        raise ExternalAgentBatchResultError("task_id is invalid", "INVALID_TASK_ID")
    return value


def _as_text(value: Any, field: str) -> str:
    if not isinstance(value, str):
        raise ExternalAgentBatchResultError(f"{field} must be a string", "INVALID_RESULT_ITEMS")
    if "\x00" in value:
        raise ExternalAgentBatchResultError(f"{field} contains a NUL character", "INVALID_RESULT_ITEMS")
    return value


def _placeholder_counter(value: str) -> Counter[str]:
    return Counter(_PLACEHOLDER_RE.findall(value))


def _source_batch_hash(items: Sequence[Mapping[str, Any]]) -> str:
    canonical = [{"index": int(item["index"]), "source": str(item["source"])} for item in items]
    return _sha256(_canonical(canonical))


class ExternalAgentBatchResultService:
    """Validate Agent results and stage them under a task-local state root."""

    def __init__(
        self,
        project_root: str | Path | None = None,
        *,
        state_root: str | Path | None = None,
        clock: Callable[[], str] | None = None,
    ) -> None:
        self.project_root = Path(project_root or Path(__file__).resolve().parents[3]).expanduser().resolve()
        self.state_root = Path(
            state_root
            or self.project_root / "Resource" / "automation_progress" / "external_agent_batches"
        ).expanduser().resolve()
        self._clock = clock or _utc_now
        self._lock = threading.RLock()
        self.state_root.mkdir(parents=True, exist_ok=True)

    def _task_dir(self, task_id: str) -> Path:
        task_id = _safe_task_id(task_id)
        path = (self.state_root / task_id).resolve()
        try:
            path.relative_to(self.state_root)
        except ValueError as exc:
            raise ExternalAgentBatchResultError("task state path escapes state root", "INVALID_TASK_ID") from exc
        return path

    def _results_path(self, task_id: str) -> Path:
        return self._task_dir(task_id) / "accepted_results.json"

    @staticmethod
    def _load_ledger(ledger: Mapping[str, Any] | str | Path) -> dict[str, Any]:
        if isinstance(ledger, Mapping):
            value = deepcopy(dict(ledger))
        elif isinstance(ledger, (str, Path)):
            path = Path(ledger).expanduser()
            try:
                value = json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError) as exc:
                raise ExternalAgentBatchResultError("batch ledger is unreadable", "LEDGER_INVALID") from exc
        else:
            raise ExternalAgentBatchResultError("batch ledger must be an object or JSON path", "LEDGER_INVALID")
        if not isinstance(value, dict):
            raise ExternalAgentBatchResultError("batch ledger must be an object", "LEDGER_INVALID")
        return value

    @staticmethod
    def _find_batch(ledger: Mapping[str, Any], batch_id: str) -> dict[str, Any]:
        batches = ledger.get("batches")
        if isinstance(batches, list):
            for batch in batches:
                if isinstance(batch, Mapping) and batch.get("batch_id") == batch_id:
                    return deepcopy(dict(batch))
        if ledger.get("batch_id") == batch_id:
            return deepcopy(dict(ledger))
        raise ExternalAgentBatchResultError("batch does not exist in ledger", "BATCH_NOT_FOUND")

    @staticmethod
    def _expected_items(batch: Mapping[str, Any]) -> list[dict[str, Any]]:
        raw_items = batch.get("items")
        if not isinstance(raw_items, list) or not raw_items:
            raise ExternalAgentBatchResultError("ledger batch has no items", "LEDGER_INVALID")
        items: list[dict[str, Any]] = []
        seen: set[int] = set()
        for item in raw_items:
            if not isinstance(item, Mapping):
                raise ExternalAgentBatchResultError("ledger item must be an object", "LEDGER_INVALID")
            index = item.get("index")
            if isinstance(index, bool) or not isinstance(index, int) or index in seen:
                raise ExternalAgentBatchResultError("ledger item index is invalid", "LEDGER_INVALID")
            source = _as_text(item.get("source", item.get("source_text")), "source")
            seen.add(index)
            entry = dict(item)
            entry["index"] = index
            entry["source"] = source
            items.append(entry)
        return sorted(items, key=lambda item: item["index"])

    @staticmethod
    def _submitted_payload(submitted: Any) -> tuple[Any, dict[str, Any]]:
        if isinstance(submitted, Mapping):
            values = dict(submitted)
            if "items" not in values:
                raise ExternalAgentBatchResultError("submitted result requires items", "INVALID_RESULT_ITEMS")
            return values.get("items"), values
        return submitted, {}

    @classmethod
    def _validate_items(cls, expected: Sequence[Mapping[str, Any]], submitted: Any) -> list[dict[str, Any]]:
        if not isinstance(submitted, list):
            raise ExternalAgentBatchResultError("items must be an array", "INVALID_RESULT_ITEMS")
        expected_by_index = {int(item["index"]): item for item in expected}
        seen: set[int] = set()
        accepted: list[dict[str, Any]] = []
        for item in submitted:
            if not isinstance(item, Mapping):
                raise ExternalAgentBatchResultError("each result item must be an object", "INVALID_RESULT_ITEMS")
            index = item.get("index")
            if isinstance(index, bool) or not isinstance(index, int) or index not in expected_by_index or index in seen:
                raise ExternalAgentBatchResultError("result item index does not match ledger", "INVALID_RESULT_ITEMS")
            source = expected_by_index[index]["source"]
            if "source" in item and _as_text(item["source"], "source") != source:
                raise ExternalAgentBatchResultError("result source does not match ledger", "SOURCE_MISMATCH")
            translation = _as_text(item.get("translation"), "translation")
            if translation.count("\n") != source.count("\n"):
                raise ExternalAgentBatchResultError(
                    "translation newline structure does not match source", "NEWLINE_MISMATCH"
                )
            if _placeholder_counter(translation) != _placeholder_counter(source):
                raise ExternalAgentBatchResultError(
                    "translation placeholders do not match source", "PLACEHOLDER_MISMATCH"
                )
            seen.add(index)
            accepted_item = {
                key: value for key, value in expected_by_index[index].items()
                if key in {"index", "source", "source_text", "item_id", "file_id", "storage_path", "text_index", "source_hash", "current_line_hash", "cache_revision"}
            }
            accepted_item.update({"index": index, "source": source, "translation": translation})
            accepted.append(accepted_item)
        if seen != set(expected_by_index):
            raise ExternalAgentBatchResultError("result does not contain every ledger item", "INVALID_RESULT_ITEMS")
        return sorted(accepted, key=lambda item: item["index"])

    @staticmethod
    def _read_document(path: Path, task_id: str) -> dict[str, Any]:
        if not path.exists():
            return {"schema": SCHEMA, "task_id": task_id, "results": []}
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ExternalAgentBatchResultError("accepted results file is unreadable", "STATE_INVALID") from exc
        if not isinstance(value, dict) or value.get("schema") != SCHEMA or value.get("task_id") != task_id:
            raise ExternalAgentBatchResultError("accepted results file schema is invalid", "STATE_INVALID")
        if not isinstance(value.get("results"), list):
            raise ExternalAgentBatchResultError("accepted results list is invalid", "STATE_INVALID")
        return value

    @staticmethod
    def _write_document(path: Path, document: Mapping[str, Any]) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + ".tmp")
        temporary.write_text(json.dumps(dict(document), ensure_ascii=False, indent=2), encoding="utf-8")
        temporary.replace(path)

    def validate_and_stage(
        self,
        ledger: Mapping[str, Any] | str | Path,
        submitted: Any,
        *,
        batch_id: str | None = None,
        task_id: str | None = None,
        source_hash: str | None = None,
        revision: int | None = None,
        idempotency_key: str | None = None,
    ) -> dict[str, Any]:
        """Validate one complete batch and append it to the task result ledger."""
        ledger_value = self._load_ledger(ledger)
        payload_items, payload = self._submitted_payload(submitted)
        task_id = _safe_task_id(task_id or payload.get("task_id") or ledger_value.get("task_id"))
        batch_id = batch_id or payload.get("batch_id")
        if not isinstance(batch_id, str) or not batch_id:
            raise ExternalAgentBatchResultError("batch_id is required", "INVALID_BATCH_ID")
        batch = self._find_batch(ledger_value, batch_id)
        expected = self._expected_items(batch)
        accepted_items = self._validate_items(expected, payload_items)

        provided_hash = source_hash if source_hash is not None else payload.get("source_hash")
        expected_hash = _source_batch_hash(expected)
        ledger_hash = batch.get("source_hash")
        if ledger_hash is not None and (not isinstance(ledger_hash, str) or ledger_hash != expected_hash):
            raise ExternalAgentBatchResultError("ledger source hash is invalid", "LEDGER_INVALID")
        if provided_hash is None:
            provided_hash = expected_hash
        if not isinstance(provided_hash, str) or not _SHA256_RE.fullmatch(provided_hash):
            raise ExternalAgentBatchResultError("source_hash must be a SHA-256 hex digest", "INVALID_SOURCE_HASH")
        if provided_hash != expected_hash:
            raise ExternalAgentBatchResultError("source hash does not match ledger", "SOURCE_HASH_MISMATCH")

        provided_revision = revision if revision is not None else payload.get("revision")
        expected_revision = batch.get("revision")
        if expected_revision is None:
            expected_revision = ledger_value.get("revision")
        if provided_revision is None:
            provided_revision = expected_revision
        if isinstance(provided_revision, bool) or not isinstance(provided_revision, int):
            raise ExternalAgentBatchResultError("revision must be an integer", "INVALID_REVISION")
        if expected_revision is not None and provided_revision != expected_revision:
            raise ExternalAgentBatchResultError("result revision is stale", "REVISION_CONFLICT")

        key = idempotency_key if idempotency_key is not None else payload.get("idempotency_key")
        if key is not None and (not isinstance(key, str) or not key or len(key) > 256):
            raise ExternalAgentBatchResultError("idempotency_key is invalid", "INVALID_IDEMPOTENCY_KEY")
        result_hash = _sha256(_canonical(accepted_items))
        fingerprint = _sha256(_canonical({"batch_id": batch_id, "source_hash": provided_hash, "revision": provided_revision, "items": accepted_items}))
        with self._lock:
            path = self._results_path(task_id)
            document = self._read_document(path, task_id)
            for record in document["results"]:
                if record.get("batch_id") != batch_id:
                    continue
                if record.get("fingerprint") == fingerprint and (key is None or record.get("idempotency_key") == key):
                    replay = deepcopy(record)
                    replay["replayed"] = True
                    return replay
                raise ExternalAgentBatchResultError("batch result already staged with different data", "IDEMPOTENCY_CONFLICT")
            record = {
                "status": "accepted", "task_id": task_id, "batch_id": batch_id,
                "source_hash": provided_hash, "revision": provided_revision,
                "result_hash": result_hash, "fingerprint": fingerprint,
                "idempotency_key": key, "accepted_at": self._clock(),
                "items": deepcopy(accepted_items), "replayed": False,
            }
            document["results"].append(record)
            document["updated_at"] = record["accepted_at"]
            self._write_document(path, document)
            return deepcopy(record)

    accept_batch_result = validate_and_stage

    def read_staged(self, task_id: str) -> dict[str, Any]:
        """Read staged records for integration by a later deterministic writer."""
        with self._lock:
            return deepcopy(self._read_document(self._results_path(_safe_task_id(task_id)), _safe_task_id(task_id)))


ExternalAgentBatchResultValidator = ExternalAgentBatchResultService

_DEFAULT_SERVICE: ExternalAgentBatchResultService | None = None
_DEFAULT_LOCK = threading.Lock()


def get_external_agent_batch_result_service() -> ExternalAgentBatchResultService:
    global _DEFAULT_SERVICE
    if _DEFAULT_SERVICE is None:
        with _DEFAULT_LOCK:
            if _DEFAULT_SERVICE is None:
                _DEFAULT_SERVICE = ExternalAgentBatchResultService()
    return _DEFAULT_SERVICE


def validate_and_stage(
    ledger: Mapping[str, Any] | str | Path,
    submitted: Any,
    **kwargs: Any,
) -> dict[str, Any]:
    return get_external_agent_batch_result_service().validate_and_stage(ledger, submitted, **kwargs)


__all__ = [
    "SCHEMA", "ExternalAgentBatchResultError", "BatchResultError",
    "ExternalAgentBatchResultService", "ExternalAgentBatchResultValidator",
    "get_external_agent_batch_result_service", "validate_and_stage",
]
